# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				cow = true
				magma_cube = true
				strider = true
				skeleton = true
				iron_golem = true
				zombified_piglin = true
				bat = true
				piglin = true
				blaze = true
				leash_knot = true
				painting = true
				experience_bottle = true
				zombie = true
				glow_squid = true
				glow_item_frame = false
				spider = true
				experience_orb = true
				creeper = true
				player = true
				enderman = true
				slime = true
				witch = true
				chicken = true
				cod = true
				salmon = true
				armor_stand = true
				sheep = true
				axolotl = true
				villager = true
				pig = true
				item_frame = true
				bee = true
				drowned = true

			[light_sources.settings.entities.goodall]
				seal = true
				red_deer = true
				manatee = true

			[light_sources.settings.entities.betternether]
				firefly = true
				naga = true

			[light_sources.settings.entities.more_babies]
				skeleton = true
				creeper = true
				spider = true
				witch = true
				glow_squid = true
				bat = true

			[light_sources.settings.entities.mca]
				female_villager = true
				male_zombie_villager = true
				female_zombie_villager = true

			[light_sources.settings.entities.adventurez]
				orc = true

			[light_sources.settings.entities.probablychests]
				stone_chest_mimic = true
				normal_chest_mimic = true
				gold_chest_mimic = true
				rocky_chest_mimic = true
				lush_chest_mimic = true

			[light_sources.settings.entities.graveyard]
				nightmare = true
				revenant = true
				skeleton_creeper = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.biomemakeover]
				owl = true
				rootling = true
				adjudicator = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				dripstone_creeper = true

			[light_sources.settings.entities.duckling]
				duck = true
				duck_egg = true

